module.exports = {
  ROLES: {
    PLATFORM_ADMIN: 'PLATFORM_ADMIN',
    BLOOD_BANK_ADMIN: 'BLOOD_BANK_ADMIN',
    DONOR: 'DONOR',
    PATIENT: 'PATIENT',
  },
  PAYMENT_TYPES: {
    PATIENT_REGISTRATION: 'PATIENT_REGISTRATION',
    TRANSFER_FEE: 'TRANSFER_FEE',
    CYCLE_REFUND: 'CYCLE_REFUND',
    PRBC_FEE: 'PRBC_FEE',
    SERVICE_CHARGE: 'SERVICE_CHARGE',
  },
  PAYMENT_STATUS: {
    CREATED: 'CREATED',
    CAPTURED: 'CAPTURED',
    REFUNDED: 'REFUNDED',
    FAILED: 'FAILED',
  },
  FEES: {
    PATIENT_REGISTRATION: 10000,   // INR 100 in paise
    TRANSFER_FEE: 54900,           // INR 549 in paise
    CYCLE_DONOR_REFUND: 40000,     // INR 400 in paise
    CYCLE_PATIENT_REFUND: 40000,   // INR 400 in paise
    CYCLE_SERVICE_CHARGE: 15000,   // INR 150 in paise
  },
  DONOR_CARD_STATUS: {
    ISSUED: 'ISSUED',
    IN_WHOLE_BLOOD: 'IN_WHOLE_BLOOD',
    IN_PRBC: 'IN_PRBC',
    RESERVED: 'RESERVED',
    TRANSFERRED: 'TRANSFERRED',
    USED: 'USED',
    EXPIRED: 'EXPIRED',
  },
  TTI_STATUS: {
    PENDING: 'PENDING',
    PASSED: 'PASSED',
    FAILED: 'FAILED',
  },
  TRANSFER_STATUS: {
    SENT: 'SENT',
    ACKNOWLEDGED: 'ACKNOWLEDGED',
    ACCEPTED: 'ACCEPTED',
    REJECTED: 'REJECTED',
    CANCELLED: 'CANCELLED',
    FULFILLED: 'FULFILLED',
  },
  EXCHANGE_TYPE: {
    BILATERAL: 'BILATERAL',
    UNILATERAL: 'UNILATERAL',
  },
  MIN_DONATION_INTERVAL_DAYS: 56,
  MIN_DONOR_WEIGHT_KG: 50,
  MIN_DONOR_AGE: 18,
  MAX_DONOR_AGE: 65,
  RESERVATION_EXPIRY_HOURS: 72,
  BLOOD_EXPIRY_DAYS: 35,
  REDLOCK_TTL_MS: 30000,
};
